// This is an autogenerated file from Firebase Studio.

export const firebaseConfig = {
  "projectId": "studio-126745911-bad1e",
  "appId": "1:400537452761:web:fa707a67ba909c31467ec8",
  "apiKey": "AIzaSyBg4giVxpT70xXVRnUVj0nlL1jnAH9-L3Y",
  "authDomain": "studio-126745911-bad1e.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "400537452761"
};
